version: "3.8"

services:
  flutter:
    build:
      context: ../flutter
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ../flutter:/app
    depends_on:
      - server

  server:
    build:
      context: ../server
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ../server:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kindred
    ports:
      - "5432:5432"