name: Upload Context to OpenAI

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * *"  # Runs daily at 12:00 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-gpt-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Package Context Files
        run: |
          tar -czf project-context.tar.gz README.md docs/ src/ || true

      - name: Upload to OpenAI API
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          RESPONSE=$(curl -s -X POST "https://api.openai.com/v1/files" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: multipart/form-data" \
            -F "file=@project-context.tar.gz" \
            -F "purpose=assistants")

          echo "Upload Response: $RESPONSE"
