name: Upload Context to OpenAI Assistant

on:
  push:
    branches:
      - main  # Runs when pushing to main
  workflow_dispatch:  # Allows manual trigger

jobs:
  upload-context:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compress Context Files
        run: |
          echo "Zipping context files..."
          zip -r project-context.zip ./context-folder/* || true

      - name: Upload Context File to OpenAI (Retrieval)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Uploading project-context.zip to OpenAI for retrieval..."
          RESPONSE=$(curl -s -X POST "https://api.openai.com/v1/files" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: multipart/form-data" \
            -F "file=@project-context.zip" \
            -F "purpose=assistants")

          echo "Upload Response: $RESPONSE"
          echo $RESPONSE | jq .

      - name: Handle API Response
        run: |
          echo "Checking API Response..."
          if [[ $RESPONSE == *"error"* ]]; then
            echo "❌ Upload failed! Response:"
            echo $RESPONSE
            exit 1
          else
            FILE_ID=$(echo $RESPONSE | jq -r '.id')
            echo "✅ File uploaded successfully! File ID: $FILE_ID"
            echo "FILE_ID=$FILE_ID" >> $GITHUB_ENV
          fi

      - name: Attach File to Assistant
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ASSISTANT_ID: ${{ secrets.OPENAI_ASSISTANT_ID }}  # Store this in GitHub Secrets
        run: |
          echo "Attaching file to assistant..."
          ATTACH_RESPONSE=$(curl -s -X POST "https://api.openai.com/v1/assistants/$ASSISTANT_ID/files" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{\"file_id\": \"$FILE_ID\"}")

          echo "Attach Response: $ATTACH_RESPONSE"
          echo $ATTACH_RESPONSE | jq .

          if [[ $ATTACH_RESPONSE == *"error"* ]]; then
            echo "❌ Failed to attach file!"
            exit 1
          else
            echo "✅ File attached successfully to assistant!"
          fi
