name: Upload Context to OpenAI Assistant

on:
  push:
    branches:
      - main  # Runs when pushing to main
  workflow_dispatch:  # Allows manual trigger

jobs:
  upload-context:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compress Context Files
        run: |
          echo "🔹 Zipping context files..."
          mkdir -p context-folder  # Ensure the folder exists
          zip -r project-context.zip ./context-folder/* || true
          
          # Verify the file exists and is not empty
          if [ ! -f "project-context.zip" ]; then
            echo "❌ Error: File project-context.zip was not created!"
            exit 1
          fi
          if [ ! -s "project-context.zip" ]; then
            echo "❌ Error: File project-context.zip is empty!"
            exit 1
          fi
          
          echo "✅ Context file successfully created."
          ls -lah project-context.zip  # Print file size for debugging

      - name: Upload Context File to OpenAI (Retrieval)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          FILE_PATH="$(pwd)/project-context.zip"
          echo "🔹 Uploading $FILE_PATH to OpenAI for retrieval..."

          RESPONSE=$(curl -s -X POST "https://api.openai.com/v1/files" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: multipart/form-data" \
            -F "file=@$FILE_PATH" \
            -F "purpose=assistants")

          echo "Upload Response: $RESPONSE"
          echo $RESPONSE | jq .

          if [[ $RESPONSE == *"error"* ]]; then
            echo "❌ Upload failed! Response: $RESPONSE"
            exit 1
          else
            FILE_ID=$(echo $RESPONSE | jq -r '.id')
            echo "✅ File uploaded successfully! File ID: $FILE_ID"
            echo "FILE_ID=$FILE_ID" >> $GITHUB_ENV
          fi

      - name: Attach File to Assistant
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ASSISTANT_ID: ${{ secrets.OPENAI_ASSISTANT_ID }}  # Store in GitHub Secrets
        run: |
          echo "🔹 Attaching file to assistant..."
          ATTACH_RESPONSE=$(curl -s -X POST "https://api.openai.com/v1/assistants/$ASSISTANT_ID/files" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{\"file_id\": \"$FILE_ID\"}")

          echo "Attach Response: $ATTACH_RESPONSE"
          echo $ATTACH_RESPONSE | jq .

          if [[ $ATTACH_RESPONSE == *"error"* ]]; then
            echo "❌ Failed to attach file!"
            exit 1
          else
            echo "✅ File attached successfully to assistant!"
          fi
